In [7]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [8]:
from sklearn.svm import SVC
from sklearn.linear_model import SGDClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [9]:
Whitewine= pd.read_csv("winequality-white.csv", delimiter=';')
Whitewine

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8,6
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,6
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,6
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
...,...,...,...,...,...,...,...,...,...,...,...,...
4893,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6
4894,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5
4895,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6
4896,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7
4897,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6

In [10]:
white_value = ['white']
Whitewine ['type'] =white_value * 4898

In [11]:
# we are creating a new column called "quality_label", we define a range and associate that range with a label
Whitewine['quality_label'] = Whitewine['quality'].apply(lambda value: 'low'
if value <= 5 else 'medium'
if value <= 7 else 'high')

# here we are transforming these labels into a categorical data type (specific to pandas) instead of a simple string
Whitewine['quality_label'] = pd.Categorical(Whitewine['quality_label'],
categories=['low', 'medium', 'high'])
Whitewine

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,type,quality_label
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8,6,white,medium
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,6,white,medium
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,6,white,medium
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6,white,medium
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6,white,medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4893,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6,white,medium
4894,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5,white,low
4895,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6,white,medium
4896,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7,white,medium
4897,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6,white,medium

In [13]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
Whitewine['quality_label'] = le.fit_transform(Whitewine['quality_label'])
Whitewine['quality_label'].head()

0    2
1    2
2    2
3    2
4    2
Name: quality_label, dtype: int32

In [25]:
X = Whitewine.drop(columns=['quality_label','type','quality', 'density', 'pH'])
y = Whitewine['quality_label']

In [26]:
y

0       2
1       2
2       2
3       2
4       2
       ..
4893    2
4894    1
4895    2
4896    2
4897    2
Name: quality_label, Length: 4898, dtype: int32

In [27]:
from sklearn.model_selection import cross_val_score, train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [35]:

from sklearn.metrics import accuracy_score 
from sklearn.ensemble import RandomForestClassifier

# define model
RF_clf = RandomForestClassifier(random_state=42)
# fit model
RF_clf.fit(X_train, y_train)
# make predictions
RF_preds = RF_clf.predict(X_test)
# check overall accuracy %
RF_acc = accuracy_score(y_test, RF_preds)

RF_acc

0.8153061224489796

In [28]:
# data normalisation with sklearn
from sklearn.preprocessing import MinMaxScaler

# fit scaler on training data
norm = MinMaxScaler().fit(X_train)

# transform training data
X_train_norm = norm.transform(X_train)

# transform testing data
X_test_norm = norm.transform(X_test)

In [36]:
from sklearn.linear_model import LogisticRegression

LR_model = LogisticRegression(max_iter=1000)

In [37]:
LR_model.fit(X_train_norm, y_train)

LogisticRegression(max_iter=1000)

In [38]:
preds = LR_model.predict(X_test_norm)
preds

array([2, 2, 2, 2, 2, 2, 1, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2,
       2, 2, 2, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 2, 1, 1, 2, 2, 1, 2, 2,
       1, 2, 1, 1, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 1, 1, 2, 1, 1, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 2, 1, 2, 2,
       2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 1, 2, 2, 2, 2, 2,
       2, 1, 2, 2, 2, 2, 2, 1, 2, 1, 2, 2, 1, 2, 1, 2, 1, 2, 2, 2, 2, 2,
       1, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 1, 2, 1, 1, 2, 2, 2, 1, 2, 2, 2,
       1, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 2, 2, 1, 2, 2, 2, 2, 2, 2, 1,
       2, 2, 2, 2, 2, 1, 2, 1, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2, 1, 2, 1,
       2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 1, 2, 2, 2, 1, 1, 2,
       2, 1, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 1, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 1, 2, 2, 2, 2, 1, 2, 2, 1, 2, 1, 2, 2, 1, 2, 2, 2, 2,
       2, 2, 2, 1, 2, 2, 2, 2, 1, 2, 1, 2, 2, 1, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 1, 2, 1, 2,
       1, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 2, 1, 2,
       1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 1, 2,
       2, 2, 2, 1, 1, 2, 2, 2, 1, 2, 1, 1, 2, 2, 2, 2, 1, 2, 1, 1, 1, 2,
       2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 1, 1, 2, 1, 2, 2, 1, 2, 1, 1, 1,
       1, 2, 2, 2, 1, 1, 2, 1, 2, 1, 2, 2, 2, 1, 2, 1, 2, 2, 1, 2, 2, 2,
       2, 2, 1, 2, 2, 1, 1, 2, 2, 2, 2, 1, 2, 1, 1, 1, 1, 1, 2, 2, 2, 2,
       2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2,
       2, 2, 2, 2, 2, 1, 2, 2, 1, 2, 1, 2, 2, 1, 2, 1, 1, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 1, 1, 2, 1, 2, 2, 1, 2, 1, 1, 2, 1, 1, 2, 2, 1, 2, 2, 1,
       1, 2, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 1, 2, 2, 1, 1, 2, 1, 2, 2, 2,
       2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2, 1, 2, 1, 1, 1, 2, 2, 2,
       2, 2, 2, 1, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1,
       2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1,
       1, 2, 1, 2, 2, 1, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2,
       1, 2, 1, 1, 2, 2, 1, 1, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2, 2, 1, 2,
       2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 1, 1, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2,
       2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       1, 2, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2, 2, 2, 1, 2, 1, 2,
       2, 1, 1, 2, 2, 2, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 2, 1, 2, 2, 2, 2, 1, 1, 2, 1, 2, 2, 2, 1, 2, 2, 2, 2, 1,
       1, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 1, 2, 1, 2, 2,
       2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 1, 2])

In [39]:
y_test

4656    2
3659    0
907     0
4352    1
3271    2
       ..
3207    2
1539    2
964     2
168     1
3661    2
Name: quality_label, Length: 980, dtype: int32

In [40]:
from sklearn.metrics import accuracy_score 

acc = accuracy_score(y_test, preds)
acc

0.7081632653061225

In [41]:
from sklearn.metrics import confusion_matrix

print("Confusion matrix:")
print(confusion_matrix(y_test, preds))

Confusion matrix:
[[  0   0  35]
 [  1 153 167]
 [  0  83 541]]

In [50]:
import numpy as np

n_estimators = np.arange(10,210,10)
max_depth = np.arange(5, 55, 5)
min_samples_split = np.arange(2, 15, 2)
max_features = ["sqrt", "log2", None]

param_grid = {
  'n_estimators': n_estimators,
  'max_depth': max_depth,
  'min_samples_split': min_samples_split,
  'max_features': max_features,
}

param_grid

{'n_estimators': array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
        140, 150, 160, 170, 180, 190, 200]),
 'max_depth': array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50]),
 'min_samples_split': array([ 2,  4,  6,  8, 10, 12, 14]),
 'max_features': ['sqrt', 'log2', None]}

In [51]:
from sklearn.model_selection import RandomizedSearchCV

# redefine model
RF_clf = RandomForestClassifier(random_state=42)

RS_grid = RandomizedSearchCV(estimator=RF_clf, param_distributions=param_grid, n_iter=15)
RS_grid

RandomizedSearchCV(estimator=RandomForestClassifier(random_state=42), n_iter=15,
                   param_distributions={'max_depth': array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50]),
                                        'max_features': ['sqrt', 'log2', None],
                                        'min_samples_split': array([ 2,  4,  6,  8, 10, 12, 14]),
                                        'n_estimators': array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150, 160, 170, 180, 190, 200])})

In [52]:
RS_grid.fit(X_train, y_train)

RandomizedSearchCV(estimator=RandomForestClassifier(random_state=42), n_iter=15,
                   param_distributions={'max_depth': array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50]),
                                        'max_features': ['sqrt', 'log2', None],
                                        'min_samples_split': array([ 2,  4,  6,  8, 10, 12, 14]),
                                        'n_estimators': array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150, 160, 170, 180, 190, 200])})

In [54]:
print(
  'best score: ', RS_grid.best_score_,
  '\nparams: ', RS_grid.best_params_
)

best score:  0.8009151744989185
params:  {'n_estimators': 40, 'min_samples_split': 4, 'max_features': 'log2', 'max_depth': 40}

In [55]:
RS_grid.cv_results_

{'mean_fit_time': array([0.75541544, 0.98568301, 1.14264784, 0.30421925, 0.22763534,
        0.8177012 , 0.97263861, 0.42636662, 2.08779249, 0.70309944,
        0.27289338, 0.49384418, 0.05362415, 1.03536143, 1.5987905 ]),
 'std_fit_time': array([0.05588437, 0.05329149, 0.07631997, 0.00577144, 0.01751155,
        0.04443415, 0.01597673, 0.035646  , 0.04991053, 0.06864554,
        0.08929533, 0.01279693, 0.00453065, 0.31437499, 0.11039266]),
 'mean_score_time': array([0.0263999 , 0.02734885, 0.03767042, 0.0119823 , 0.01078825,
        0.02333031, 0.0277359 , 0.01891198, 0.0244607 , 0.02604113,
        0.00792489, 0.02173543, 0.00251522, 0.03096256, 0.03671203]),
 'std_score_time': array([0.0072858 , 0.00593398, 0.00521618, 0.00498307, 0.00465287,
        0.00458855, 0.00512283, 0.01569285, 0.00490895, 0.00489203,
        0.00617733, 0.01199219, 0.00385073, 0.01240125, 0.02485575]),
 'param_n_estimators': masked_array(data=[130, 190, 190, 60, 40, 160, 190, 90, 180, 160, 40, 190,
                    10, 180, 170],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False],
        fill_value=999999),
 'param_min_samples_split': masked_array(data=[12, 10, 2, 6, 4, 10, 6, 2, 14, 4, 12, 12, 4, 12, 8],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False],
        fill_value=999999),
 'param_max_features': masked_array(data=['log2', 'log2', 'log2', 'log2', 'log2', 'sqrt', 'sqrt',
                    'log2', None, 'log2', 'sqrt', 'sqrt', None, 'sqrt',
                    None],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_max_depth': masked_array(data=[45, 15, 50, 25, 40, 15, 25, 10, 35, 10, 50, 5, 5, 35,
                    10],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False],
        fill_value=999999),
 'params': [{'n_estimators': 130,
   'min_samples_split': 12,
   'max_features': 'log2',
   'max_depth': 45},
  {'n_estimators': 190,
   'min_samples_split': 10,
   'max_features': 'log2',
   'max_depth': 15},
  {'n_estimators': 190,
   'min_samples_split': 2,
   'max_features': 'log2',
   'max_depth': 50},
  {'n_estimators': 60,
   'min_samples_split': 6,
   'max_features': 'log2',
   'max_depth': 25},
  {'n_estimators': 40,
   'min_samples_split': 4,
   'max_features': 'log2',
   'max_depth': 40},
  {'n_estimators': 160,
   'min_samples_split': 10,
   'max_features': 'sqrt',
   'max_depth': 15},
  {'n_estimators': 190,
   'min_samples_split': 6,
   'max_features': 'sqrt',
   'max_depth': 25},
  {'n_estimators': 90,
   'min_samples_split': 2,
   'max_features': 'log2',
   'max_depth': 10},
  {'n_estimators': 180,
   'min_samples_split': 14,
   'max_features': None,
   'max_depth': 35},
  {'n_estimators': 160,
   'min_samples_split': 4,
   'max_features': 'log2',
   'max_depth': 10},
  {'n_estimators': 40,
   'min_samples_split': 12,
   'max_features': 'sqrt',
   'max_depth': 50},
  {'n_estimators': 190,
   'min_samples_split': 12,
   'max_features': 'sqrt',
   'max_depth': 5},
  {'n_estimators': 10,
   'min_samples_split': 4,
   'max_features': None,
   'max_depth': 5},
  {'n_estimators': 180,
   'min_samples_split': 12,
   'max_features': 'sqrt',
   'max_depth': 35},
  {'n_estimators': 170,
   'min_samples_split': 8,
   'max_features': None,
   'max_depth': 10}],
 'split0_test_score': array([0.79081633, 0.79081633, 0.80102041, 0.79464286, 0.7997449 ,
        0.78571429, 0.79846939, 0.77806122, 0.77040816, 0.77806122,
        0.78826531, 0.73979592, 0.72704082, 0.78954082, 0.7755102 ]),
 'split1_test_score': array([0.79719388, 0.79209184, 0.81377551, 0.80357143, 0.80994898,
        0.79081633, 0.80994898, 0.78061224, 0.79464286, 0.77295918,
        0.80229592, 0.71811224, 0.71683673, 0.7997449 , 0.76658163]),
 'split2_test_score': array([0.79336735, 0.79591837, 0.7997449 , 0.80102041, 0.80739796,
        0.78954082, 0.79336735, 0.78061224, 0.80229592, 0.78571429,
        0.79591837, 0.74872449, 0.75      , 0.79209184, 0.79081633]),
 'split3_test_score': array([0.77650064, 0.78033206, 0.78799489, 0.77905492, 0.78799489,
        0.78033206, 0.78799489, 0.7752235 , 0.77266922, 0.77650064,
        0.76756066, 0.75095785, 0.7394636 , 0.77905492, 0.76372925]),
 'split4_test_score': array([0.77777778, 0.77905492, 0.79565773, 0.78927203, 0.79948914,
        0.77650064, 0.79310345, 0.7688378 , 0.76500639, 0.76756066,
        0.77139208, 0.71775223, 0.71775223, 0.77650064, 0.76117497]),
 'mean_test_score': array([0.78713119, 0.7876427 , 0.79963869, 0.79351233, 0.80091517,
        0.78458082, 0.79657681, 0.7766694 , 0.78100451, 0.7761592 ,
        0.78508647, 0.73506855, 0.73021868, 0.78738662, 0.77156248]),
 'std_test_score': array([0.00841692, 0.00671638, 0.00840472, 0.00878444, 0.00766776,
        0.00544259, 0.00746205, 0.00439212, 0.0146767 , 0.0059868 ,
        0.01355205, 0.01448222, 0.01281684, 0.00857238, 0.01077371]),
 'rank_test_score': array([ 7,  5,  2,  4,  1,  9,  3, 11, 10, 12,  8, 14, 15,  6, 13])}

In [56]:
import pandas as pd

grid_results = pd.concat([
  pd.DataFrame(RS_grid.cv_results_["params"]),
  pd.DataFrame(RS_grid.cv_results_["mean_test_score"], columns=["Accuracy"])
], axis=1)

grid_results

    n_estimators  min_samples_split max_features  max_depth  Accuracy
0            130                 12         log2         45  0.787131
1            190                 10         log2         15  0.787643
2            190                  2         log2         50  0.799639
3             60                  6         log2         25  0.793512
4             40                  4         log2         40  0.800915
5            160                 10         sqrt         15  0.784581
6            190                  6         sqrt         25  0.796577
7             90                  2         log2         10  0.776669
8            180                 14         None         35  0.781005
9            160                  4         log2         10  0.776159
10            40                 12         sqrt         50  0.785086
11           190                 12         sqrt          5  0.735069
12            10                  4         None          5  0.730219
13           180                 12         sqrt         35  0.787387
14           170                  8         None         10  0.771562

In [57]:
from sklearn.model_selection import GridSearchCV

# redefine model
RF_clf = RandomForestClassifier(random_state=42)

GS_grid = GridSearchCV(estimator=RF_clf, param_grid=param_grid)
GS_grid

GridSearchCV(estimator=RandomForestClassifier(random_state=42),
             param_grid={'max_depth': array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50]),
                         'max_features': ['sqrt', 'log2', None],
                         'min_samples_split': array([ 2,  4,  6,  8, 10, 12, 14]),
                         'n_estimators': array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150, 160, 170, 180, 190, 200])})

In [59]:
GS_grid.fit(X_train, y_train)

KeyboardInterrupt: